spring:
  datasource:
    url: jdbc:mysql://um-practice-db.chltvfsuvhy2.us-east-2.rds.amazonaws.com:3306/spring_test
    username: admin
    password: um133133
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        show-sql: true
        ddl-auto: create
        format_sql: true
    generate-ddl: true



logging:
  level:
    org.hibernate: info
    org.hibernate.SQL: debug
    org.hibernate.type: trace